# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '新简约' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 新简约

  target '新简约Tests' do
    inherit! :search_paths
    # Pods for testing


  end

  target '新简约UITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod ‘AFNetworking’,‘~> 3.0’
pod ‘Masonry’
pod ’SDWebImage’
pod ’SVProgressHUD’
pod ‘FMDB’

end
